#!/bin/sh
uci set upnpd.@upnpd[0].enabled=1
uci commit upnpd
uci set autoreboot.@login[0].enable=1
uci commit autoreboot

uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

uci delete dropbear.@dropbear[0].Interface
uci commit dropbear

#uci set network.wan6.sourcefilter=0
#uci commit network

echo "#!/bin/sh
ebtables -t broute -A BROUTING -p ! ipv6 -j DROP -i $(uci -q get network.wan6.ifname)
brctl addif br-lan $(uci -q get network.wan6.ifname)
#/etc/init.d/odhcpd stop
#/etc/init.d/odhcpd disable
exit 0" >> /etc/ipv6brctl.sh
chmod a+x /etc/ipv6brctl.sh

echo "listener 1883
allow_anonymous true" >> /etc/mosquitto/mosquitto.conf

exit 0