#!/bin/sh
uci add luci command
uci set luci.@command[0].name='dynv6'
uci set luci.@command[0].command='token=uqZfUZmsmtaeZTCkic1PQ_aYJRp1Kn /etc/dynv6.sh fanyue.v6.navy'
uci add luci command
uci set luci.@command[1].name='wgethosts2'
uci set luci.@command[1].command='/etc/wgethosts2.sh'
uci commit luci

uci set network.wan6.sourcefilter=0
uci commit network

uci set dhcp.lan.ra_default=1
uci add_list dhcp.@dnsmasq[0].addnhosts='/etc/hosts2'
uci commit dhcp

uci set upnpd.@upnpd[0].enabled=1
uci commit upnpd
uci set autoreboot.@login[0].enable=1
uci commit autoreboot

uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

uci delete dropbear.@dropbear[0].Interface
uci commit dropbear

uci set socat.@global[0].enable=1
uci set socat.55555555555555555555555555555555='config'
uci set socat.55555555555555555555555555555555.firewall_accept='1'
uci set socat.55555555555555555555555555555555.enable='1'
uci set socat.55555555555555555555555555555555.remarks='5555'
uci set socat.55555555555555555555555555555555.protocol='port_forwards'
uci set socat.55555555555555555555555555555555.family='6'
uci set socat.55555555555555555555555555555555.proto='tcp'
uci set socat.55555555555555555555555555555555.reuseaddr='1'
uci set socat.55555555555555555555555555555555.dest_proto='tcp4'
uci set socat.55555555555555555555555555555555.dest_ip='127.0.0.1'
uci set socat.55555555555555555555555555555555.dest_port='80'
uci set socat.55555555555555555555555555555555.listen_port='5555'
uci commit socat

echo "#!/bin/sh
wget --no-check-certificate -O /etc/hosts2 https://raw.hellogithub.com/hosts
exit 0" >> /etc/wgethosts2.sh
chmod a+x /etc/wgethosts2.sh
echo "0 */1 * * * /etc/wgethosts2.sh" >> /etc/crontabs/root

echo "ip6tables -t nat -A POSTROUTING -o $(uci -q get network.wan6.ifname) -j MASQUERADE" >> /etc/firewall.user
chmod a+x /etc/dynv6.sh
echo "0 */1 * * * token=uqZfUZmsmtaeZTCkic1PQ_aYJRp1Kn /etc/dynv6.sh fanyue.v6.navy" >> /etc/crontabs/root
echo "listener 1883" >> /etc/mosquitto/mosquitto.conf
echo "allow_anonymous true" >> /etc/mosquitto/mosquitto.conf

exit 0