#!/bin/sh

echo -e '542056\n542056' | passwd root
uci set system.@system[0].hostname='DOCKER'
uci set firewall.@defaults[0].forward='ACCEPT'
uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

uci delete dropbear.@dropbear[0].Interface
uci commit dropbear
uci set upnpd.@upnpd[0].enabled=1
uci commit upnpd

uci del dhcp.lan.ra
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.start='100'
uci del dhcp.lan.limit='150'
uci del dhcp.lan.leasetime='12h'
uci set dhcp.lan.ignore='1'

uci set dhcp.@dnsmasq[0].addnhosts='/etc/dnsmasq.hosts'
uci commit dhcp

uci set network.lan.ipaddr=$LANIP
uci set network.lan.gateway=$LANGATEWAY
uci set network.lan.dns=$LANDNS
uci set network.wan6=interface
uci set network.wan6.device=$WAN6ETH
uci set network.wan6.proto='dhcpv6'

#uci del network.globals
uci del network.globals.ula_prefix
#uci set network.globals.packet_steering='1'

uci commit network

echo "0 3 * * * curl -o /etc/dnsmasq.hosts https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts && /etc/init.d/dnsmasq restart" >> /etc/crontabs/root

chmod 4755 /etc/openclash/core/clash_meta

uci set openclash.config.enable='1'
uci del openclash.@authentication[0]
uci del openclash.config.dashboard_password

uci set openclash.config.auto_restart='1'
uci set openclash.config.auto_restart_week_time='*'
uci set openclash.config.auto_restart_day_time='3'

uci set openclash.config.config_path='/etc/openclash/config/clash.yaml'
uci set openclash.config.config_reload='1'

#uci set openclash.config.chnr_auto_update='1'
#uci set openclash.config.geo_auto_update='1'
#uci set openclash.config.geoip_auto_update='1'
#uci set openclash.config.geosite_auto_update='1'
#uci set openclash.config.other_rule_auto_update='1'

uci set openclash.config.auto_update='1'
uci set openclash.config.config_auto_update_mode='1'
uci set openclash.config.config_update_interval='90'

uci add openclash config_subscribe
uci set openclash.@config_subscribe[-1].enabled='1'
uci set openclash.@config_subscribe[-1].name='clash'
uci set openclash.@config_subscribe[-1].address=$CLASH_URL
uci set openclash.@config_subscribe[-1].sub_ua='clash.meta'

uci set openclash.config.en_mode='fake-ip-mix'

#uci set openclash.config.operation_mode='redir-host'
#uci set openclash.config.en_mode='redir-host-mix'

uci set openclash.config.stack_type='mixed'

#uci set openclash.config.skip_proxy_address='1'
uci set openclash.config.ipv6_dns='1'

uci set openclash.config.enable_custom_dns='1'
uci set openclash.config.enable_tcp_concurrent='1'

for section in $(uci show openclash | grep -E '@dns_servers\[.*\]\.(group|enabled)' | awk -F. '/group=/ {gsub(/'\''/,""); if($3 ~ /group=nameserver/) print $1"."$2} /enabled=1/ {print $1"."$2}'); do 
    uci set "${section}.enabled=0";
done && uci commit openclash

uci set openclash.@dns_servers[-1]=dns_servers
uci set openclash.@dns_servers[-1].enabled='1'
uci set openclash.@dns_servers[-1].group='nameserver'
uci set openclash.@dns_servers[-1].type='udp'
uci set openclash.@dns_servers[-1].ip='192.168.5.82'

uci commit openclash

exit 0
