#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set upnpd.@upnpd[0].enabled=1
uci commit upnpd

uci set firewall.@zone[1].input='ACCEPT'
uci commit firewall

uci delete dropbear.@dropbear[0].Interface
uci commit dropbear

#uci set network.wan6.sourcefilter=0
#uci commit network
#uci delete dhcp.lan.dhcpv6
#uci delete dhcp.lan.ra
#uci commit dhcp

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

exit 0