#!/bin/sh
uci add luci command
uci set luci.@command[1].name='wgethosts2'
uci set luci.@command[1].command='/etc/wgethosts2.sh'
uci add luci command
uci set luci.@command[2].name='ipv6brctl'
uci set luci.@command[2].command='/etc/ipv6brctl.sh'
uci commit luci
uci add_list dhcp.@dnsmasq[0].addnhosts='/etc/hosts2'
uci commit dhcp

echo "#!/bin/sh
ebtables -t broute -A BROUTING -p ! ipv6 -j DROP -i $(uci -q get network.wan6.ifname)
brctl addif br-lan $(uci -q get network.wan6.ifname)
/etc/init.d/odhcpd stop
#/etc/init.d/odhcpd disable
exit 0
" >> /etc/ipv6brctl.sh
chmod a+x /etc/ipv6brctl.sh
echo "104.16.2.80 javdb.com" >> /etc/hosts
echo "# GitHub Start 80:FA:5B:2B:85:8A" >> /etc/hosts2
echo "#!/bin/sh
wget --no-check-certificate -O /etc/hosts2 https://raw.hellogithub.com/hosts
exit 0" >> /etc/wgethosts2.sh
chmod a+x /etc/wgethosts2.sh
echo "0 */1 * * * /etc/wgethosts2.sh" >> /etc/crontabs/root

exit 0