name: build-QEMU-armsr-armv8

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openwrt

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:  
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Building armsr-armv8 QEMU ImmortalWrt
        run: |
          luci_version="${{ github.event.inputs.luci_version }}"
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/DIY/aarch64/uci-defaults:/home/build/immortalwrt/files/etc/uci-defaults" \
            -v "${{ github.workspace }}/DIY/aarch64/.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/DIY/aarch64/build.sh:/home/build/immortalwrt/build.sh" \
            immortalwrt/imagebuilder:armsr-armv8-openwrt-25.12 /bin/bash /home/build/immortalwrt/build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@main
        with:
          platforms: linux/arm64
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Organize files
        id: organize
        run: |
          cp ${{ github.workspace }}/bin/targets/*/*/*.tar.gz ${{ github.workspace }}
          sudo chmod a+x ${{ github.workspace }}/*.tar.gz
          cd ${{ github.workspace }}
          gzip -d *.tar.gz
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          docker buildx build -f $GITHUB_WORKSPACE/DIY/aarch64/Dockerfile --platform linux/arm64 -t openwrt --output=type=docker .
          docker buildx build -f $GITHUB_WORKSPACE/DIY/aarch64/Dockerfile --platform linux/arm64 -t ghcr.io/this-ooo/openwrt:latest . --push
          rm -f *.tar
          docker save openwrt  > docker-img-${IMAGE_NAME}.tar
          echo "firmware=$PWD" >> $GITHUB_OUTPUT

      - name: Upload - push to artifact file
        uses: actions/upload-artifact@main
        with:
          name: Docker-OpenWrt-aarch64
          path: ${{ steps.organize.outputs.firmware }}/*.tar
