#=================================================
# Build OpenWrt AArch64
#=================================================

name: Build OpenWrt AArch64

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: DIY/aarch64/aarch64.config
  DIY_P1_SH: DIY/diy-part1.sh
  DIY_P2_SH: DIY/diy-part2.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@main
  
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
  
      - name: Clone source code
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone -b $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
  
      - name: Load custom feeds
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH
  
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a
  
      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a
  
      - name: Load custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_P2_SH
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P2_SH
          cp -rf $GITHUB_WORKSPACE/DIY/aarch64/uci-defaults/settings-aarch64 package/base-files/files/etc/uci-defaults/settings
          mkdir -p package/openclash/luci-app-openclash/root/etc/openclash/core
          LATEST_TAG=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep -o '"tag_name": "[^"]*' | cut -d'"' -f4)
          echo "Latest mihomo version: $LATEST_TAG"
          curl -L "https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_TAG}/mihomo-linux-arm64-${LATEST_TAG}.gz" | gzip -d > package/openclash/luci-app-openclash/root/etc/openclash/core/clash_meta
  
      - name: Download package
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
  
      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
  
      - name: Check space usage
        if: (!cancelled())
        run: df -hT
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
              
      - name: Organize files
        id: organize
        run: |
          cd openwrt/bin/targets/*/*
          gzip -dc *-rootfs.tar.gz
          
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          docker buildx build -f $GITHUB_WORKSPACE/DIY/aarch64/Dockerfile --platform linux/arm64 -t openwrt --output=type=docker .
          docker buildx build -f $GITHUB_WORKSPACE/DIY/aarch64/Dockerfile --platform linux/arm64 -t ghcr.io/this-ooo/openwrt:latest . --push
          rm -f *-rootfs.tar
          docker save openwrt  > docker-img-openwrt.tar

          echo "firmware=$PWD" >> $GITHUB_OUTPUT

      - name: Upload - push to artifact file
        uses: actions/upload-artifact@main
        with:
          name: Docker-OpenWrt-aarch64
          path: ${{ steps.organize.outputs.firmware }}/*.tar
